### ISSUE TITLE
Error trying to use eclipse plugin

### ISSUE THREAD

**Issue by magick93** [vaulttec/isis-script#1]
Hi

This looks like a really excellent plugin. I was just thinking that it would be interesting to do a sculptor cartridge for Apache Isis, then found this.

Anyway, when trying to run it, I am not getting eclipe recognize the .isis extension, and get the below error:

eclipse.buildId=4.5.0.I20150603-2000
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -data file:/home/anton/workspaces/tradeworks-modeling/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

org.vaulttec.isis.script.ui
Error
Sat Jul 18 00:18:32 CEST 2015
FrameworkEvent ERROR

org.osgi.framework.BundleException: Could not resolve module: org.vaulttec.isis.script.ui [1821]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"

```
at org.eclipse.osgi.container.Module.start(Module.java:434)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

eclipse.buildId=4.5.0.I20150603-2000
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -data file:/home/anton/workspacesmodeling/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

**Comment by magick93** [comment]
I tried on a clean install in eclipse modeling, and this is the error:

eclipse.buildId=4.5.0.I20150603-2000
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.modeling.product
Command-line arguments:  -data file:/home/anton/workspaces/isis/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.modeling.product

org.vaulttec.isis.script.ui
Error
Sat Jul 18 11:38:44 CEST 2015
FrameworkEvent ERROR

org.osgi.framework.BundleException: Could not resolve module: org.vaulttec.isis.script.ui [792]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"

```
at org.eclipse.osgi.container.Module.start(Module.java:434)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

Does this mean it requires java 8?

**Comment by magick93** [comment]
Ok, yes that was the problem. Eclipse needed to be set to use Java 8. 

Can close this issue now.

**Comment by tjuerge** [comment]
> Ok, yes that was the problem. Eclipse needed to be set to use Java 8.

This was by accident (I'm running Eclipse with Java 8). I will make sure that for this plugin only Java 7 is required.

**Comment by tjuerge** [comment]
A new version of the plugin (including support for entity repositories #2) which doesn't require Java 8 is available from the [update site](https://raw.githubusercontent.com/vaulttec/isis-script/updatesite/).

**Comment by magick93** [comment]
Thanks Torsten, much appreciated.
