### ISSUE TITLE
no viable alternative at input 'repository'

### ISSUE THREAD

**Issue by magick93** [vaulttec/isis-script#3]
Hi

I'm trying the example given in the readme, and there seems to be an issue with the respository keyword.

In Ecliipse I am getting: "no viable alternative at input 'repository'".

I'm not sure if this is related, but I also see:

```
eclipse.buildId=4.5.0.I20150603-2000
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

org.apache.log4j
Error
Sun Jul 19 00:31:06 CEST 2015
org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator  - Error calling inferrer


java.lang.NullPointerException
    at org.vaulttec.isis.script.jvmmodel.IsisJvmModelInferrer._infer(IsisJvmModelInferrer.java:81)
    at org.vaulttec.isis.script.jvmmodel.IsisJvmModelInferrer.infer(IsisJvmModelInferrer.java:577)
    at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:382)
    at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:240)
    at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
    at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareBatchTypeResolver.getEntryPoints(LogicalContainerAwareBatchTypeResolver.java:44)
    at org.eclipse.xtext.xbase.typesystem.internal.DefaultBatchTypeResolver.getTypeResolver(DefaultBatchTypeResolver.java:63)
    at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:49)
    at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:1)
    at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
    at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:46)
    at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
    at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:71)
    at org.eclipse.xtext.xbase.resource.BatchLinkableResource.resolveLazyCrossReferences(BatchLinkableResource.java:165)
    at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:528)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.postParse(XtextDocumentReconcileStrategy.java:174)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:152)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:66)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:445)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:425)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$DocumentListener$1.exec(XtextReconciler.java:136)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$DocumentListener$1.exec(XtextReconciler.java:1)
    at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:121)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:428)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.process(XtextDocument.java:337)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$DocumentListener.performNecessaryUpdates(XtextReconciler.java:133)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.updateContentBeforeRead(XtextDocument.java:249)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:518)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
    at org.eclipse.xtext.ui.editor.syntaxcoloring.HighlightingReconciler$2.run(HighlightingReconciler.java:320)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by tjuerge** [comment]
Stacktraces from Jave code generated by Xtend are not useable most of the time. Without having the correlation of the corresponding line in the Xtend source (which is provided by the generated ".trace" files used by the Eclipse debugger) we can only guess the method.

But the hint with the NullPointerException is helpful. It seems that I missed a null check for an incomplete model element for which no Java code can be generated yet. So I need your model source code at the time the exception occurs to reproduces this symptom.

**Comment by magick93** [comment]
Hi Torsten

The contents of the isis script that is, I think, causing, the is:

```
package domainapp.dom.modules.simple

import org.apache.isis.applib.annotation.DomainObject
import org.apache.isis.applib.annotation.DomainObjectLayout
import org.apache.isis.applib.annotation.Action
import javax.jdo.annotations.Queries
import javax.jdo.annotations.Query

@DomainObject(objectType = "SIMPLE")
@DomainObjectLayout(bookmarking = AS_ROOT)
@Queries(#[
    @Query(name = "findByName", language = "JDOQL",
        value = "SELECT FROM domainapp.dom.modules.simple.StrategyBuilder WHERE name.indexOf(:name) >= 0")
])
entity StrategyBuilder {

    property String name

    event UpdateNameDomainEvent

    @Action(domainEvent = UpdateNameDomainEvent)
    action updateName(String newName) {
        setName(newName)
    }  

    repository {

        action listAll() {
            container.allInstances(StrategyBuilder)
        }

        action findByName(String name) {
            container.allMatches(new QueryDefault(StrategyBuilder,
                "findByName", "name", name))
        }
    }

}
```

Please let me know if you need anything else

**Comment by tjuerge** [comment]
The Readme was updated to show a complete example (including package and imports).

**Comment by tjuerge** [comment]
Your script is correct - only the import for `QueryDefault` is missing.
If you get any error with the editor then please create a screenshot and attach it to an issue.

**Comment by magick93** [comment]
Ok, I have copied the full script as in the readme, and just change the class name, and other references, and am getting design time errors - see image.
![selection_285](https://cloud.githubusercontent.com/assets/2173213/8766006/80187712-2e28-11e5-9ab1-686dbeb76033.png)

**Comment by tjuerge** [comment]
The screenshot shows that the DSL editor doesn't support the keyword "repository". So it seems you're using the initial version of the Isis Script editor.
Please update the Isis Script plugin to version "1.0.0.201507181458".

**Comment by magick93** [comment]
I have tried installing, reinstalling and updating - but I keep getting version '1.0.0.201507051948'.

**Comment by tjuerge** [comment]
The outdated artefacts are removed from the updatesite. Please try again.
If this doesn't work then uninstall the plugin (via the Eclipse About dialog) and install from scratch.

**Comment by magick93** [comment]
I've tried uninstalling and reinstalling, and now I getting:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: https://raw.githubusercontent.com/vaulttec/isis-script/updatesite/features/org.vaulttec.isis.script.ide_1.0.0.201507051948.jar.
https://raw.githubusercontent.com/vaulttec/isis-script/updatesite/features/org.vaulttec.isis.script.ide_1.0.0.201507051948.jar

It seems the old version is hardcoded somewhere in the update site.

**Comment by magick93** [comment]
In the artificacts.jar - the version is hardcoded there.

**Comment by tjuerge** [comment]
Strange, the [GitHub history of `artifacts.jar`](https://github.com/vaulttec/isis-script/commits/updatesite/artifacts.jar) shows that it was overwritten with a newer one referencing the artifacts with the timestamp from last friday (201507051948). It seems that your Eclipse p2 installer has cached the outdated version of `artifacts.jar`.

How about uninstalling the plugin, deleting the update site, restarting Eclipse, re-adding the update site and re-installing the plugin to make sure that the latest version of `artifacts.jar` gets fetched from the update site?

**Comment by magick93** [comment]
I have tried your above suggestion.
I have even searched my entire filesystem for anything that contains  '1.0.0.201507051948' - and did find some files in the eclipse installation directory. I deleted these.
Yet when I try to do a fresh install of the plugin, again it tries to install the old version.

**Comment by tjuerge** [comment]
Very strange. If I'm installing the plugin in my local Eclipse installation as follows then the latest version gets fetched and everything works as expected:

![screen shot 2015-07-20 at 21 12 12](https://cloud.githubusercontent.com/assets/2626998/8784923/8735c32c-2f24-11e5-9c2f-63e072fb3475.png)
![screen shot 2015-07-20 at 21 16 48](https://cloud.githubusercontent.com/assets/2626998/8785036/4188e286-2f25-11e5-9df0-78c2963c0fb1.png)
![screen shot 2015-07-20 at 21 18 49](https://cloud.githubusercontent.com/assets/2626998/8785037/47cf5864-2f25-11e5-8089-d9107a630bba.png)
